QueryGenerationTask:
  description: |
    User Query: {user_query}
    The user has provided additional clarification: {user_details}.
    The current date is {current_date}.
    Your task is generate search queries and use a provided tools to search on the web
    **Query Generation:**
      - Based on the user's original question and any additional details, generate up to **{no_keywords} distinct search queries**.
      - Each query should focus on one specific aspect of the original question.
      - Queries should be diverse, if the topic is broad, generate more than 1 query.
      - Don't generate multiple similar queries, 1 is enough.
    finaly pass the generated list of queries to provided tools to search on the web
  expected_output: |
    A Confirmation message for completed successfully

ReportTask:
  description: |
    Generate a comprehensive response formatted in **Markdown** using the provided search results (`{search_results}`).
    Your response must directly answer the user's question: {user_query} and include any necessary clarification provided in `{user_details}`.
    ### Content Requirements:
    - A clear and descriptive **Title**.
    - A well-structured **Answer** that uses Markdown formatting (e.g., headings, lists, bold/italic text).
    
    Be written in the **same language** used in the user's question
    Do **NOT** use Markdown code blocks (no triple backticks like ``` or ```markdown).
    Do **NOT** include raw code; the output should be readable like an article or blog post.

  expected_output: |
    A Markdown-formatted article with a title and a detailed answer, without code blocks.
