QueryGenerationTask:
  description: |
    The user has provided additional clarification: {user_details}.
    The current date is {current_date}.
    Your task is generate search queries and use a provided tools to search on the web
    **Query Generation:**
      - Based on the user's original question and any additional details, generate up to **{no_keywords} distinct search queries**.
      - Each query should focus on one specific aspect of the original question.
      - Queries should be diverse, if the topic is broad, generate more than 1 query.
      - Don't generate multiple similar queries, 1 is enough.
    finaly pass the generated list of queries to provided tools to search on the web
  expected_output: |
    A Confirmation message for completed successfully

ReportTask:
  description: |
    Generate a comprehensive, json based on the provided search results {search_results}.
    Your answer must be answer for user question and clarification: {user_details}.
    CONTENT REQUIREMENTS:
    - Title
    - Answer
    Do NOT use json code blocks (no ```json or ```)
    Do NOT include any images, charts, or external links or Urls
  expected_output: |
    A JSON object conforming to the `QuickReport` model.