PlanningTask:
  description: |
    You are a smart planning agent.  
    Your job is to generate a **clear, structured, and comprehensive plan or outline** for the user's request or question.

    The user's input is: "{user_query}"  
    The user has provided the following additional details: "{user_details}"  
    The current date is: {current_date}

    Your output should:
    - Contain 3 clearly numbered steps, sections, or points  
    - Be high-level (no detailed explanation or content)  
    - Be **relevant, practical, and actionable** based on the user's goal  
    - Be suitable whether the query is a research question, personal goal, or a learning objective

    You may include:
    - Tasks to complete  
    - Resources to search for  
    - Topics to explore  
    - Actions to take  
    - Areas to consider

    Adapt the outline structure depending on the type of request.

  expected_output: |
    A list of 3 numbered and well-structured points that guide the user in exploring or achieving what they asked for.

WebSearchTask:
  description: |
    Your job is to search the web for relevant information based on the provided plan.
    Your task is generate search queries and use a provided tools to search on the web
    **Query Generation:**
      - Based on the plan, generate up to length of the plan points distinct search queries.
      - Don't generate multiple similar queries, 1 is enough.
    loop for each query and pass it to provided tools to search on the web
    - finally use provided tool to save all links on json file
  expected_output: |
    A confirmation message without any details.

WebScraperTask:
  description: |
    Your job is to scrape the web pages.
    - Use the scrape_tool to scrape the relevant page content.

  expected_output: |
    A Confirmation message without any details.


ReportWriterTask:
  description: |
    Using the following plan: {research_plan} and all provided scraped content in json files, you will write a comprehensive report.

    Steps to follow:
    1. Read the plan from the file `{research_plan}`.
    2. Read all the scraped content from the provided JSON files.
    3. Analyze the content and structure it into a professional research report.
    4. Generate a comprehensive response formatted in **Markdown** based on the plan and scraped content.

    - Your response must directly answer the user's question: {user_query} and include any necessary clarification provided in `{user_details}`.
    ### Report structure:
    - Title: A clear and concise title that reflects the main topic of the report.
    - Introduction: A brief introduction that outlines the purpose and scope of the report.
    - Body: The main content of the report, organized with the plan
    - Conclusion: A summary of the key findings and recommendations.

    Be written in the **same language** used in the user's question
    Do **NOT** use Markdown code blocks (no triple backticks like ``` or ```markdown).

  expected_output: |
    A Markdown-formatted long article with a title and a detailed answer, without code blocks.