QueryGenerationTask:
  description: |
    You have received the following user query: '{user_query}'.
    The user has provided additional clarification: {user_details}.
    The current date is {current_date}.
    Your task is to understand the user's intent clearly and proceed in two steps:
    **Query Generation:**
      - Based on the user's original question and any additional details, generate up to **{no_keywords} distinct search queries**.
      - Each query should focus on one specific aspect of the original question.
      - Queries should be diverse, if the topic is broad, generate more than 1 query.
      - Don't generate multiple similar queries, 1 is enough.
  expected_output: |
    A JSON object conforming to the SuggestedSearchQueries model.

ResearcherTask:
  description: |
    Task instruction:
    - search on the internet based on {search_queries} provided.
    - You have to collect results from multiple search queries.
    - use search tool to search for all provided search queries.
    - Do NOT search each query separately. Use the tool that accepts a list of queries.
  expected_output: |
    A confirmation message that the results were collected and saved successfully.